apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pfdemo-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: pfdemo-deploy
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi